name: Auto Version Update

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip-version]')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Get commit count for version
      id: version
      run: |
        # Usar el número de commits como versión patch
        COMMIT_COUNT=$(git rev-list --count HEAD)
        NEW_VERSION="2.1.$COMMIT_COUNT"
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "Nueva versión calculada: v$NEW_VERSION"

    - name: Update version in files
      run: |
        # Actualizar package.json
        sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"${{ steps.version.outputs.version }}\"/g" package.json
        
        # Actualizar index.html
        sed -i "s/<span class=\"version-info\">v[0-9.]*<\/span>/<span class=\"version-info\">v${{ steps.version.outputs.version }}<\/span>/g" index.html
        
        echo "✅ Archivos actualizados con versión v${{ steps.version.outputs.version }}"

    - name: Commit and push if changed
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        git add package.json index.html
        
        if git diff --staged --quiet; then
          echo "No hay cambios de versión para commitear"
        else
          git commit -m "🔖 Auto-update version to v${{ steps.version.outputs.version }} [skip-version]"
          git push
          echo "✅ Versión commiteada y pusheada a main"
        fi
        
        git add package.json index.html
        
        if git diff --staged --quiet; then
          echo "No hay cambios de versión para commitear"
        else
          git commit -m "🔖 Auto-update version to v${{ steps.version.outputs.version }} [skip-version]"
          git push
          echo "✅ Versión commiteada y pusheada a main"
        fi